# Topgrade Configuration
# https://github.com/topgrade-rs/topgrade

[misc]
assume_yes = true
cleanup = true
pre_sudo = true
disable = ["emacs", "vim", "node", "conda", "julia", "dotnet", "mise"]
no_retry = true
notify_each_step = true

[brew]
greedy_cask = true

[python]
enable_pip_review = false

[git]
max_concurrency = 5
